# =============================================================================
# Feuji LLM Kit — Tenant Infrastructure Blueprint
# Phase 1 Stage 4: Generated by AI from approved ResourcePlan
# Phase 2 OPTIMA-AI: Reads outputs from this to identify optimizable resources
# =============================================================================
terraform {
  required_version = ">= 1.7.0"
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.80"
    }
  }
  backend "azurerm" {
    resource_group_name  = var.state_rg
    storage_account_name = var.state_sa
    container_name       = "tfstate"
    key                  = "tenants/prod.tfstate"  # overridden per tenant at runtime
  }
}

provider "azurerm" {
  features {}
  use_oidc = true  # Workload Identity — no client secrets (ADR-004)
}

locals {
  # Mandatory tags — OPA policy enforces all 5 tags on every resource
  mandatory_tags = {
    Project     = var.project_name
    Environment = var.environment
    TenantId    = var.tenant_id
    Compliance  = var.compliance
    ManagedBy   = "terraform"
  }
}

# ── Resource Group ────────────────────────────────────────────────────────────
resource "azurerm_resource_group" "main" {
  name     = join("-", ["rg", var.tenant_id, var.environment])
  location = var.location
  tags     = local.mandatory_tags
}

# ── Networking ────────────────────────────────────────────────────────────────
resource "azurerm_virtual_network" "main" {
  name                = join("-", ["vnet", var.tenant_id])
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  tags                = local.mandatory_tags
}

resource "azurerm_subnet" "aks" {
  name                 = "subnet-aks"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.1.0/24"]
}

resource "azurerm_subnet" "db" {
  name                 = "subnet-db"
  resource_group_name  = azurerm_resource_group.main.name
  virtual_network_name = azurerm_virtual_network.main.name
  address_prefixes     = ["10.0.2.0/24"]
  delegation {
    name = "postgres"
    service_delegation {
      name = "Microsoft.DBforPostgreSQL/flexibleServers"
    }
  }
}

# ── PostgreSQL Flexible + pgvector ────────────────────────────────────────────
# OPTIMA-AI Phase 2 reads: postgresql_fqdn from outputs
# OPTIMA-AI Recommendation OPT-03: right-size IVFFlat probes
resource "azurerm_postgresql_flexible_server" "main" {
  name                          = join("-", ["psql", var.tenant_id])
  resource_group_name           = azurerm_resource_group.main.name
  location                      = azurerm_resource_group.main.location
  version                       = "15"
  delegated_subnet_id           = azurerm_subnet.db.id
  public_network_access_enabled = false   # OPA policy: no public DB endpoint
  storage_mb                    = 32768
  sku_name                      = "GP_Standard_D4s_v3"
  zone                          = "1"
  tags                          = local.mandatory_tags
}

# ── AKS Cluster ───────────────────────────────────────────────────────────────
# OPTIMA-AI Phase 2 reads: aks_cluster_name from outputs
# OPTIMA-AI Recommendation OPT-01: right-size node_count during off-peak
resource "azurerm_kubernetes_cluster" "main" {
  name                = join("-", ["aks", var.tenant_id])
  location            = azurerm_resource_group.main.location
  resource_group_name = azurerm_resource_group.main.name
  dns_prefix          = var.tenant_id
  default_node_pool {
    name           = "default"
    node_count     = 2      # OPTIMA-AI OPT-01: reduce to 1 during off-peak
    vm_size        = "Standard_D4s_v3"
    vnet_subnet_id = azurerm_subnet.aks.id
  }
  identity { type = "SystemAssigned" }
  tags = local.mandatory_tags
}

# ── Key Vault ─────────────────────────────────────────────────────────────────
# OPTIMA-AI Phase 2 reads: key_vault_uri from outputs
resource "azurerm_key_vault" "main" {
  name                = join("-", ["kv", var.tenant_id])
  resource_group_name = azurerm_resource_group.main.name
  location            = azurerm_resource_group.main.location
  sku_name            = "standard"
  tenant_id           = data.azurerm_client_config.current.tenant_id
  tags                = local.mandatory_tags
}

data "azurerm_client_config" "current" {}
